### ISSUE TITLE
Request to implement D3DXIntersectTri functionality in DXMath

### ISSUE THREAD

**Issue by unistellar** [JeremyAnsel/JeremyAnsel.DirectX#1]
First, thanks for the great work! All I need is the math and this package is a light and fast alternative to XNA.

I can't seem to find the D3DXIntersectTri functionality baked into DXMath yet. D3DXIntersectTri is a ray-triangle intersection presumably based on the Möller–Trumbore algorithm: 

http://www.cs.virginia.edu/~gfx/Courses/2003/ImageSynthesis/papers/Acceleration/Fast%20MinimumStorage%20RayTriangle%20Intersection.pdf

The old D3DXIntersectTri signature looks like this:

BOOL WINAPI D3DXIntersectTri 
(
    CONST D3DXVECTOR3 *p0,           // Triangle vertex 0 position
    CONST D3DXVECTOR3 *p1,           // Triangle vertex 1 position
    CONST D3DXVECTOR3 *p2,           // Triangle vertex 2 position
    CONST D3DXVECTOR3 *pRayPos,      // Ray origin
    CONST D3DXVECTOR3 *pRayDir,      // Ray direction
    FLOAT *pU,                         // Barycentric Hit Coordinates
    FLOAT *pV,                         // Barycentric Hit Coordinates
    FLOAT *pDist                      // Ray-Intersection Parameter Distance
);

Takes 3 points of a triangle, a ray origin and ray direction, and returns true/false whether it intersected within the bounds of the triangle, U and V coordinates along with a distance.

**Comment by JeremyAnsel** [comment]
Hello,

There is the `JeremyAnsel.DirectX.DXMath.Collision.TriangleTest.Intersects` method:
`public static bool TriangleTest.Intersects(XMVector origin, XMVector direction, XMVector v0, XMVector v1, XMVector v2, out float distance)`

This method compute a ray-triangle intersection and returns the distance.

Do you need the U and V coordinates? If needed, I can add a method that returns those values.

**Comment by unistellar** [comment]
I do need the U and V and distance... sorry I thought I responded already but I don't see my post!

**Comment by JeremyAnsel** [comment]
I"ve added `public static bool Intersects(XMVector origin, XMVector direction, XMVector v0, XMVector v1, XMVector v2, out float uCoordinate, out float vCoordinate, out float distance)`.
