### ISSUE TITLE
Draw the outline of a text

### ISSUE THREAD

**Issue by MarkhusGenferei** [JeremyAnsel/JeremyAnsel.DirectX#5]
In order to draw the outline of a text [like this](https://www.graphicsmill.com/docs/gm5/DrawingTextwithOutline.htm), examples found on the web instruct to 

- Get the fontFace of the font to use (`DWriteFontFace`)
- Using `fontFace.GetGlyphIndices()`, get the indices of the text's glyphs in the font
- Create a `D2D1PathGeometry` and its `D2D1GeometrySink`
- Ask `fontFace.GetGlyphRunOutline(...glyphIndices[]...)` to fill that sink with the glyphs' outline
- Draw and/or Fill the resulting geometry
 

Unfortunately, it looks like `DWriteFontFace.GetGlyphIndices()` and `DWriteFontFace.GetGlyphRunOutline()` are not implemented yet.

Would it be possible to remedy this ?
Thank you in advance !

**Comment by JeremyAnsel** [comment]
Hello,
I've implemented the remaining DWriteFontFace methods.

**Comment by MarkhusGenferei** [comment]
Thank you very much for reacting so quickly !

After a few trials and errors, I was able to [make it work](https://kdrive.infomaniak.com/app/share/185799/75ec8e15-94d4-4060-b91f-54ee8b40f2be). To do so, the last parameter of `DWriteFontFace.GetGlyphRunOutline()` must be the `sink.Handle` instead of the `sink `object itself.

```c#
fontFace.GetGlyphRunOutline(fontSize, indices, null, null, false, false, sink.Handle); 
```

Suggestion : make `GetGlyphRunOutline()` in DWriteFontFace.cs handle this implementation detail.

Thank you again !

**Comment by JeremyAnsel** [comment]
The `D2D1` library already depends on the `DWrite` library. So the `DWrite` library can't depend on the `D2D1` library.
One solution would be using reflection but it's slower than directly using the `Handle` property.
Another solution would be to create an interface in a base library with the `Handle` property. But I'm not sure if this would be good to do that for only a few methods.
The `Handle` property contains the real COM object. The different classes are wrappers around the COM objects.

**Comment by MarkhusGenferei** [comment]
Thank you for your prompt reply. I did'nt realize the dependency issue. 
For others, may be the documentation could mention that the sink Handle is expected as argument here.
